#!/bin/bash
# change this file to your needs

echo "Adding some modules"

# module add the_module_you_need_but_dont_deserve
module add gcc-10.2

echo "#################"
echo "    COMPILING    "
echo "#################"

cd src/ && make

echo "#################"
echo "     RUNNING     "
echo "#################"

time nice -n +19 ./network
